<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Store;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Store $viewModelStore */
$viewModelStore = $viewModels->require(Store::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

// $title = (string) $block->getTitle();
$height = $block->getHeight();
$items = $block->getItems() ?? [];
if (is_object($items) && $items instanceof Iterator) {
    $items = iterator_to_array($items);
}
if (!$itemCount = count($items)) {
    return '';
}
$sliderItemRenderer = $block->getChildBlock('slider.item.template');
$sliderIndex = 1;
?>
<script>
    'use strict';

    function initSliderComponent() {
        return {
            active: 0,
            itemCount: 0,
            getSlider() {
                return this.$root.querySelector('.js_slides');
            },
            pageSize: 1,
            pageFillers: 0,
            calcPageSize() {
                const slider = this.getSlider();
                if (slider) {
                    this.itemCount = slider.querySelectorAll('.js_slide').length;
                    this.pageSize = Math.round(slider.clientWidth / slider.querySelector('.js_slide').clientWidth);
                    this.pageFillers = (
                        this.pageSize * Math.ceil(this.itemCount / this.pageSize)
                    ) - this.itemCount;
                }
            },
            calcActive() {
                const slider = this.getSlider();
                if (slider) {
                    const sliderItems = this.itemCount + this.pageFillers;
                    const calculatedActiveSlide = slider.scrollLeft / (slider.scrollWidth / sliderItems);
                    this.active = Math.round(calculatedActiveSlide / this.pageSize) * this.pageSize;
                }
            },
            scrollPrevious() {
                this.scrollTo(this.active - this.pageSize);
            },
            scrollNext() {
                console.log(this.active, this.itemCount)
                this.scrollTo(this.active + this.pageSize);
            },
            scrollTo(idx) {
                const slider = this.getSlider();
                if (slider) {
                    const slideWidth = slider.scrollWidth / (this.itemCount + this.pageFillers);
                    slider.scrollLeft = Math.floor(slideWidth) * idx;
                    this.active = idx;
                }
            },
            skipCarouselToNavigation(navSelector) {
                const element = document.getElementById(navSelector)
                if (element) {
                    element.scrollIntoView({behavior: 'smooth', block: 'end'});
                    const button = element.querySelector('button:not([disabled])');
                    this.$nextTick(() => button && button.focus({preventScroll: true}))
                }
            }
        }
    }
</script>
<?php if ($items): ?>
    <section class="relative group"
         x-data="initSliderComponent()"
         x-init="calcPageSize();"
         x-id="['slider-nav', 'slider-end', 'slider-desc']"
         @resize.window.debounce="calcPageSize(); $nextTick( function() { calcActive() })"
         role="group"
         aria-roledescription="<?= $escaper->escapeHtml(__('Slider')) ?>"
         aria-label="<?= $escaper->escapeHtml(__('Latest items')) ?>"
         :aria-describedby="$id('slider-desc')"
    >
        <span
            class="sr-only"
            :id="$id('slider-desc')"
            tabindex="-1"
        >
                <?= $escaper->escapeHtml(__('Navigating through the elements of the carousel is possible using the tab key. You can skip the carousel or go straight to carousel navigation using the skip links.')) ?>
        </span>
        <a
            :href="`#${$id('slider-end')}`"
            class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
        >
            <?= $escaper->escapeHtml(__('Press to skip the slider')) ?>
        </a>
        <button
            x-show="itemCount > pageSize"
            type="button"
            class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
            @click.prevent="skipCarouselToNavigation($id('slider-nav'))"
        >
            <?= $escaper->escapeHtml(__('Press to go to carousel navigation')) ?>
        </button>
        <div class="relative w-full overflow-x-hidden focus-within:ring-1 active:ring-0 ring-blue-500 ring-opacity-50">
            <div class="relative flex flex-nowrap w-full overflow-auto transition-all js_slides snap"
                 @scroll.debounce="calcActive"
            >
                <?php foreach ($items as $item): ?>
                    <div role="group"
                         x-id="['slide-desc']"
                         aria-roledescription="<?= $escaper->escapeHtml(__('Slide')) ?>"
                         :aria-hidden="<?= (int) $sliderIndex ?> > active && <?= (int) $sliderIndex ?> <= (active + pageSize) ? 'false' : 'true'"
                         aria-label="<?= $escaper->escapeHtmlAttr(__('Slide %1 of %2', $sliderIndex++, count($items))) ?>"
                         :aria-describedby="$id('slide-desc')"
                         class="relative flex shrink-0 w-full py-1 js_slide"
                    >
                        <?= $sliderItemRenderer->setItem($item)
                            ->setData('height', $height)
                            ->toHtml() ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

        <template x-if="itemCount > pageSize">
            <div
                role="group"
                aria-label="<?= $escaper->escapeHtml(__('Slide controls')) ?>"
                :id="$id('slider-nav')"
            >
                <div class="opacity-0 group-hover:md:opacity-100 absolute z-10 top-1/2 -translate-y-1/2 md:px-5 lg:px-11 flex justify-between w-full">
                    <button
                        role="button"
                        aria-label="<?= $escaper->escapeHtml(__('Previous slide')) ?>"
                        class="w-9 h-9 rounded-full md:w-11 md:h-11 bg-[rgba(18,18,18,0.40)] hover:bg-[rgba(18,18,18,0.80)] flex items-center justify-center shadow-md !fill-base-white"
                        :class="{ 'pointer-events-none' : active === 0 }"
                        @click="scrollPrevious"
                    >
                        <?= $heroicons->chevronLeftHtml("w-6 h-6 text-white", 64, 64, ['aria-hidden' => 'true']) ?>
                    </button>

                    <button
                        role="button"
                        aria-label="<?= $escaper->escapeHtml(__('Next slide')) ?>"
                        class="w-9 h-9 rounded-full md:w-11 md:h-11 bg-[rgba(18,18,18,0.40)] hover:bg-[rgba(18,18,18,0.80)] flex items-center justify-center shadow-md !fill-base-white"
                        :class="{ 'pointer-events-none' : active === itemCount-1 }"
                        @click="scrollNext"
                    >
                        <?= $heroicons->chevronRightHtml("w-6 h-6 text-white", 64, 64, ['aria-hidden' => 'true']) ?>
                    </button>
                </div>

                <!-- <div class="opacity-0 group-hover:opacity-100 flex gap-4 justify-center items-center mt-7 absolute z-10 w-full bottom-4 lg:bottom-8">
                    <?php for ($i=0; $i < $itemCount; $i++): ?>
                        <button
                            role="button"
                            aria-label="<?= $escaper->escapeHtmlAttr(__('Show slide %1 of %2', $i + 1, $itemCount)) ?>"
                            class="w-3 h-3 md:w-3.5 md:h-3.5 shadow rounded-full cursor-pointer group-hover:bg-white-500"
                            @click="scrollTo(<?= (int) $i ?>)"
                            :class="{
                                'w-[14px] h-[14px] md:w-[14px] md:h-[14px] lg:w-[15px] lg:h-[15px] border-[3px] border-white': active === <?= (int) $i ?>,
                                'w-2 h-2 md:w-2.5 md:h-2.5 lg:w-3 lg:h-3 bg-white': active !== <?= (int) $i ?>,
                                'hidden': (pageSize !== 1 && !!(<?= (int) $i ?> % pageSize))
                            }"
                        >
                        </button>
                    <?php endfor; ?>
                </div> -->
            </div>
        </template>
        <span :id="$id('slider-end')" tabindex="-1"></span>
    </section>
<?php endif ?>