<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<div class="text-gray-700 bg-red-500 body-font border-t">
    <div class="container lg:py-8 py-12 mx-auto">
        <div class="flex flex-wrap order-first gap-y-6 sm:gap-y-16 items-center">
            <div class="flex w-full sm:w-1/2">
                <?= $block->getChildHtml('footer-newsletter-content') ?>
            </div>
            <div class="flex w-full flex-col sm:flex-row sm:w-1/2 sm:justify-end">
                <?= $block->getChildHtml('form.subscribe') ?>
            </div>
        </div>
    </div>
</div>